### PR TITLE
Fix device class in some entities

### PR DESCRIPTION
**Pull request by elchininet**
In some entities, like `battery` ones, the `original_device_class` property in the more-info `___entry` property is not ready when the dialog opens. This was provoking that these entitites were ignored when tried to filter them using their device class.

This pull request reads the `original_device_class` property with a promise, making sure that it is resolved when it is properly retrieved or its value is `null`.

Closes: #13

### CODE REVIEW

**Comment by elchininet** [comment]
@Mariusthvdb,
Test this one with your set up and let me know if it fixes the issue or if it creates any unwanted behaviour.

**Comment by Mariusthvdb** [comment]
thank you, and yes, can confirm no more history on battery device_class:

Scherm­afbeelding 2024-04-27 om 12 46 01

Scherm­afbeelding 2024-04-27 om 12 46 12


thanks @elchininet

**Review by Mariusthvdb — APPROVED** [review]
seems fixed, no more history displayed, thank you

**Comment by Mariusthvdb** [comment]
thx for the merge, much appreciated!

**Comment by elchininet** [comment]
@Mariusthvdb,
I forgot that you didn't have the proper setup to trigger a release. I will let you know when I am ready because you need to un-protect the main branch to allow me to do it. But at some moment I will send you some instructions so you will be able to do it from your side. Are you on a Mac or a Windows device?

**Comment by Mariusthvdb** [comment]
on Mac here, thx

**Comment by Mariusthvdb** [comment]
tbh, I am uncertain of the state this PR has, was it released already?
I am still running the local resource, but would love to have this out in the open.
Just let me know how to open the repo up so you can merge it this time?

**Comment by elchininet** [comment]
Hi @Mariusthvdb,
I have inspected the source code of the latest release and this change is not there.
We need to sync, you unprotect the branch, I push a tag and that should trigger a deployment and a release, and after that you can protect it again.
It would be good to give you the steps to install a package manager, git, and any other front-end tool needed to do this by yourself.
First thing is to install git: https://git-scm.com/download/mac
Try to install it, the easiest path is to install XCode (it comes with Git).

**Comment by Mariusthvdb** [comment]
check please, I've unprotected it

**Comment by elchininet** [comment]
Hey @Mariusthvdb,
I didn't see your last comment.
Can I try a deployment?
Regards

**Comment by elchininet** [comment]
Done, you can put the protection again.

**Comment by Mariusthvdb** [comment]
Thank you very much !

**Pull request merged**
