### PR TITLE
Add new options to manage the header history icon

### PR DESCRIPTION
**Pull request by elchininet**
This pull request adds new options to manage the history icon on the header of more-info dialogs:

#### hide_header_history_icon

Hides the header history icon.

```yaml
custom_more_info:
  hide_header_history_icon:
    # It is also possible to set a boolean value for everything
    # all: true
    by_glob:
      ...
    by_domain:
      ...
    by_device_class:
      ...
    by_entity_id:
      ...
```

#### unhide_header_history_icon

Unhides the header history icon.

```yaml
custom_more_info:
  unhide_header_history_icon:
    # It is also possible to set a boolean value for everything
    # all: true
    by_glob:
      ...
    by_domain:
      ...
    by_device_class:
      ...
    by_entity_id:
      ...
```

#### auto_hide_header_history_icon

Hides the header history icon automatically if the history and logbook have been hidden form that entity.

```yaml
custom_more_info:
  auto_hide_header_history_icon: true
``` 

>Note: as part of this pull request, the `home-assistant-query-selector` dependency has been updates to its major version.

### CODE REVIEW

**Comment by Mariusthvdb** [comment]
cant wait to test this, thank you!
does this also auto hide the button if the user uses
```
hide_history:
  by_xxx:
```
Because that would make sense?
or, would you use it the other way around.

tbh, it's a bit confusing to me having both. But maybe as a dev you see the added value of having a button to hide and a section to hide (while both being for history)

**Comment by elchininet** [comment]
>cant wait to test this, thank you!

Please, test it deeply. As you see, it could be seen as just three options but it introduces a lot of code and complexities.

>does this also auto hide the button if the user uses
>```hide_history:```
>```  by_xxx:```

No, hiding the history doesn‘t hide the button because that button also contains the logbook panel, if one hides both then the button hides (if one uses `auto_hide_header_history`). The name is confusing though because Home Assistant named it  as "History" but it contains also "Logbook".

image


>tbh, it's a bit confusing to me having both.

[Well, that was you requested earlier](https://github.com/Mariusthvdb/custom-more-info/pull/2#issuecomment-1869523137) ;)

Normally, I do not like the "auto" things (better if it is through an option) but anything is possible. It is your call. Just let me know what would be the best way and I can implement it here in this pull request.

**Comment by Mariusthvdb** [comment]
>  if one hides both then the button hides (if one uses auto_hide_header_history).


sorry, yes, that is exactly what I meant, and I can confirm this to work nicely now.
set it to auto-hide and hide both logbook and history on an entity makes the icon disappear.

which brings me to the naming of the option. should we no add the concept of the 'button' or 'icon' to that, just like your PR does?

I feel it would help in expressing what the option does. the header-history-item on itself is a bit vague, but adding either of those 2 (button/icon) or maybe even 'tab' would be helpful.

hide-header-history-tab, or hide-history-button, something like those?

**Comment by Mariusthvdb** [comment]
found an issue:
```
hide_header_history:

  by_domain:
    - input_datetime
    - automation
    - script
    - sun
 ```

doesnt work for sun.

**Comment by elchininet** [comment]
>which brings me to the naming of the option. should we no add the concept of the 'button' or 'icon' to that, just like your PR does?

Makes sense to me, which one would you choose?

>do we also have an 'all' setting for that? or would it be simplest to do that with a glob

I forgot about it, no need to, it should be easy to implement.

>found an issue:
>doesnt work for sun. Nor does:

I need to check how the layout is on that entity, maybe it is different.

**Comment by Mariusthvdb** [comment]
> > which brings me to the naming of the option. should we no add the concept of the 'button' or 'icon' to that, just like your PR does?
> 
> Makes sense to me, which one would you choose?

even HA cant make up their mind ;-)

Scherm­afbeelding 2024-01-05 om 21 06 57

but I believe we should go for the concept 'icon', and it is not a true button at all.

`hide-header-history-icon` would be perfect, albeit a bit long. But because of that it stands out nicely against the `hide-history` option

> > do we also have an 'all' setting for that? or would it be simplest to do that with a glob
> 
> I forgot about it, no need to, it should be easy to implement.

cool, no hurry, could be a separate PR if you'd like and merge this first

> > found an issue:
> > doesnt work for sun. Nor does:
> 
> I need to check how the layout is on that entity, maybe it is different.

O sorry, I completely forgot to do that myself..  I figured it would be because of not having a unique_id so not UI configurable...

**Comment by elchininet** [comment]
I don't see anything weird with the layout, I need to check the properties of the elements in those entities.

**Comment by elchininet** [comment]
@Mariusthvdb,
I have pushed the rename of the options and also the possibility of a boolean value named `all`, if it is set in true it hides (or unhides) the icon for any entity.

**Comment by elchininet** [comment]
Also, the `sun.sun` entity should be fixed. Try also with other entities to see if you find failures in them.

**Comment by Mariusthvdb** [comment]
> Also, the `sun.sun` entity should be fixed. Try also with other entities to see if you find failures in them.

nice! can confirm that using the new hide option for the icon like this:

```
auto_hide_header_history_icon: true

hide_header_history_icon:

  by_domain:
    - input_datetime
    - automation
    - script
    - cover
    - group

  by_entity_id:
    - sun.sun
```

removes the icon for all groups and the sun.sun correctly! so cool this, thanks for your effort!


I take it this is also changed to use the new `_icon` suffix?
```
auto_hide_header_history_icon: true
```

**Review by Mariusthvdb — APPROVED** [review]
all seems well now, so marking approved!

hurray

**Comment by elchininet** [comment]
>I take it this is also changed to use the new _icon suffix?

Yes

**Comment by elchininet** [comment]
Make a release, so I can submit a pull request to add the plugin in HACS. The sooner, the best.

**Comment by Mariusthvdb** [comment]
consider that done, please check

**Pull request merged**
